services:
  archidocs:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
      # Add any environment variables your application needs here 

  terminal:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: bash
    stdin_open: true
    tty: true 