services:
  # Main service for document generation
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./backend/backend/templates:/app/templates
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
    ports:
      - "8501:8501"  # Expose Streamlit's default port
    command: streamlit run frontend/app.py
    restart: unless-stopped 