name: Run Tests On File Changes

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker context
        run: cp docker/.dockerignore.dev .dockerignore
      
      - name: Build and run tests
        run: |
          docker-compose -f docker/docker-compose.dev.yml build test-specific
          docker-compose -f docker/docker-compose.dev.yml run --rm test-specific python -m unittest discover -s tests

  build-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker context
        run: cp docker/.dockerignore .dockerignore
      
      - name: Build production image
        run: |
          docker-compose -f docker/docker-compose.yml build
