name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: archidocs:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create directory structure
      run: |
        mkdir -p templates/files
        mkdir -p outputs
    
    - name: Run tests in Docker container
      run: |
        docker run --rm -v $(pwd)/templates:/app/templates -v $(pwd)/outputs:/app/outputs archidocs:test python -m unittest discover -s tests -p "test_*.py"
    
    - name: Run specific test file in Docker container
      run: |
        docker run --rm -v $(pwd)/templates:/app/templates -v $(pwd)/outputs:/app/outputs archidocs:test python tests/test_generate_docx.py 