name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: archidocs:test
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          type=gha
        cache-to: |
          type=local,dest=/tmp/.buildx-cache-new,mode=max
          type=gha,mode=max
    
    # Temp fix for https://github.com/docker/build-push-action/issues/252
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    
    - name: Create directory structure
      run: |
        mkdir -p templates/files
        mkdir -p outputs
    
    - name: Copy test files
      run: |
        # Copy a test DOCX file for PDF conversion testing
        # Use a placeholder if none exists
        if [ ! -f "test_data/test_document.docx" ]; then
          mkdir -p test_data
          # Create a simple test DOCX using LibreOffice in the Docker container
          docker run --rm -v $(pwd):/app archidocs:test bash -c '
            echo "Test content" > /tmp/test.txt
            libreoffice --headless --convert-to docx --outdir /app/test_data /tmp/test.txt
            mv /app/test_data/test.docx /app/test_data/test_document.docx
          '
        fi
        cp -f test_data/test_document.docx outputs/ || echo "No test document available"
    
    # Run tests in parallel for speed
    - name: Run all tests
      run: |
        docker run --rm \
          -v $(pwd):/app \
          archidocs:test \
          bash -c "python -m unittest discover -s tests -p 'test_*.py' -v" 