name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directory structure
      run: |
        mkdir -p templates/files
        mkdir -p outputs
        
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"
    
    - name: Run specific test file
      run: |
        python tests/test_generate_docx.py 